name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create config.js from Secrets
        run: |
          # This command still correctly places the config file inside the mobile folder
          echo "const firebaseConfig = ${{ secrets.FIREBASE_CONFIG }};" > mobile/config.js
          echo "const GEMINI_API_KEY = '${{ secrets.GEMINI_API_KEY }}';" >> mobile/config.js

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # --- THE FIX IS HERE ---
          # Upload the entire repository from the root directory '.'
          path: '.'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
